# Generated by Django 4.1.1 on 2022-09-21 04:27

from django.db import migrations
from users.models import Vendor


class Migration(migrations.Migration):

    def custom_task(self, schema_editor):
        
        Vendor = self.get_model("users","Vendor")
        for vendor in Vendor.objects.all():
            vendor.objects.create(name="Mic")
         
 
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop)
    ]
