# Generated by Django 4.1.1 on 2022-09-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_movies_viewers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viewers",
            old_name="name",
            new_name="vname",
        ),
    ]
